### PR TITLE
Science structure changes

### PR DESCRIPTION
**Pull request by phantamanta44**
mostly just changes uint8 positional controls to float32 velocity controls. might need to coordinate with low-level controls team to make sure the motor drivers interpret the packets correctly

### CODE REVIEW

**Review by alexp205 — CHANGES_REQUESTED** [review]
turns out build is supposed to be there, pls remove from gitignore and add back those files

**Comment by phantamanta44** [comment]
whoops

**Review by alexp205 — CHANGES_REQUESTED** [review]
All our linear actuators and motors are controlled by int values, so we don't need to worry about floats anymore. You can switch these back to ints and we don't need to cast anymore

**Comment by phantamanta44** [comment]
by "int" you mean a signed 8-bit int?

**Comment by alexp205** [comment]
In BCL, int8 should be fine (so yeah, int8_t). Then in WRaptorGateway, everything is static cast to unsigned (for reasons I'm still trying to parse, but I'm pretty sure that's on Bijan's end) of the same size

**Comment by phantamanta44** [comment]
so i'm currently `static_cast`ing to int8_t in the gateway, but i don't think it should make a difference because the packet ends up with the exact same structure

**Review by alexp205 — APPROVED** [review]
looks good, thanks

**Pull request merged**
